--------------------------------------------------------
--  파일이 생성됨 - 토요일-12월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CART_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_CART_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FREEBOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_FREEBOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MARKETORDER_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_MARKETORDER_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTICEBOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_NOTICEBOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PHOTOBOARD_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_PHOTOBOARD_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PLANNER_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_PLANNER_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCTREPLY_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_PRODUCTREPLY_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT_IDX
--------------------------------------------------------

   CREATE SEQUENCE  "SIGDOLAGI"."SEQ_PRODUCT_IDX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."CART" 
   (	"CART_IDX" NUMBER, 
	"PROD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PROD_COUNT" NUMBER, 
	"PROD_TOTPRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAVORITE
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."FAVORITE" 
   (	"EMAIL" VARCHAR2(30 BYTE), 
	"TNAME" VARCHAR2(20 BYTE), 
	"BOARD_IDX" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FREEBOARD
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."FREEBOARD" 
   (	"FREEBOARD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(90 BYTE), 
	"CONTENT" VARCHAR2(900 BYTE), 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"POSTDATE" DATE DEFAULT sysdate, 
	"NICKNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INQUIRYBOARD
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."INQUIRYBOARD" 
   (	"INQUIRYBOARD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(90 BYTE), 
	"CONTENT" VARCHAR2(900 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARKETORDER
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."MARKETORDER" 
   (	"ORDER_IDX" NUMBER, 
	"CART_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PROD_COUNT" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"MESSAGE" VARCHAR2(100 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(30 BYTE), 
	"PAYMENT" NUMBER, 
	"POINT" NUMBER, 
	"PAYMENT_DATE" DATE DEFAULT sysdate, 
	"ZIPCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."MEMBER" 
   (	"EMAIL" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(30 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"ZIPCODE" VARCHAR2(10 BYTE), 
	"MAILING" VARCHAR2(10 BYTE), 
	"SMS" VARCHAR2(10 BYTE), 
	"GRADE" VARCHAR2(10 BYTE) DEFAULT 'Normal', 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MYPAGE
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."MYPAGE" 
   (	"EMAIL" VARCHAR2(30 BYTE), 
	"PHOTO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICEBOARD
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."NOTICEBOARD" 
   (	"NOTICEBOARD_IDX" NUMBER, 
	"ADMIN_NAME" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(90 BYTE), 
	"CONTENT" VARCHAR2(900 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHOTOBOARD
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PHOTOBOARD" 
   (	"PHOTOBOARD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(90 BYTE), 
	"CONTENT" VARCHAR2(900 BYTE), 
	"VISITCOUNT" NUMBER DEFAULT 0, 
	"REGIDATE" DATE DEFAULT sysdate, 
	"OFILE" VARCHAR2(50 BYTE), 
	"SFILE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACE
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PLACE" 
   (	"PLANNER_IDX" NUMBER, 
	"LOT_ADDR" VARCHAR2(100 BYTE), 
	"ROAD_ADDR" VARCHAR2(100 BYTE), 
	"PLACE_NAME" VARCHAR2(100 BYTE), 
	"PLACE_CATEGORY" VARCHAR2(30 BYTE), 
	"PLACE_TELECOM" VARCHAR2(30 BYTE), 
	"X_POINT" VARCHAR2(30 BYTE), 
	"Y_POINT" VARCHAR2(30 BYTE), 
	"PLACE_URL" VARCHAR2(50 BYTE), 
	"MEMO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANNER
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PLANNER" 
   (	"PLANNER_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"CATE" VARCHAR2(30 BYTE), 
	"PLAN_START" VARCHAR2(50 BYTE), 
	"PLAN_END" VARCHAR2(50 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"NICKNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PRODUCT" 
   (	"PROD_IDX" NUMBER, 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"PROD_NAME" VARCHAR2(100 BYTE), 
	"PROD_PRICE" NUMBER, 
	"PROD_SALE" NUMBER, 
	"PROD_THUMBNAIL" VARCHAR2(50 BYTE), 
	"PROD_DETAIL" VARCHAR2(50 BYTE), 
	"SELLER" VARCHAR2(30 BYTE), 
	"IMG1" VARCHAR2(50 BYTE), 
	"IMG2" VARCHAR2(50 BYTE), 
	"IMG3" VARCHAR2(50 BYTE), 
	"IMG4" VARCHAR2(50 BYTE), 
	"IMG5" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTREPLY
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PRODUCTREPLY" 
   (	"REPLY_IDX" NUMBER, 
	"PROD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"IMAGE" VARCHAR2(50 BYTE), 
	"SCORE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_QNA
--------------------------------------------------------

  CREATE TABLE "SIGDOLAGI"."PRODUCT_QNA" 
   (	"QNA_IDX" NUMBER, 
	"PROD_IDX" NUMBER, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"CONTENT" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"SECRET" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SIGDOLAGI.CART
SET DEFINE OFF;
Insert into SIGDOLAGI.CART (CART_IDX,PROD_IDX,EMAIL,PROD_COUNT,PROD_TOTPRICE) values (1,20,'foo@gmail.com',13,118500);
Insert into SIGDOLAGI.CART (CART_IDX,PROD_IDX,EMAIL,PROD_COUNT,PROD_TOTPRICE) values (2,18,'foo@gmail.com',3,41700);
Insert into SIGDOLAGI.CART (CART_IDX,PROD_IDX,EMAIL,PROD_COUNT,PROD_TOTPRICE) values (5,19,'foo@gmail.com',3,44700);
REM INSERTING into SIGDOLAGI.FAVORITE
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.FREEBOARD
SET DEFINE OFF;
Insert into SIGDOLAGI.FREEBOARD (FREEBOARD_IDX,EMAIL,TITLE,CONTENT,VISITCOUNT,POSTDATE,NICKNAME) values (1,null,'안녕하세요?','반갑습니당',0,to_date('23/12/08','RR/MM/DD'),null);
Insert into SIGDOLAGI.FREEBOARD (FREEBOARD_IDX,EMAIL,TITLE,CONTENT,VISITCOUNT,POSTDATE,NICKNAME) values (3,null,'22332','asdfasdf',0,to_date('23/12/08','RR/MM/DD'),null);
Insert into SIGDOLAGI.FREEBOARD (FREEBOARD_IDX,EMAIL,TITLE,CONTENT,VISITCOUNT,POSTDATE,NICKNAME) values (2,null,'asdfsadf','asdfasdfsadfasdfasdf',0,to_date('23/12/08','RR/MM/DD'),null);
REM INSERTING into SIGDOLAGI.INQUIRYBOARD
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.MARKETORDER
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.MEMBER
SET DEFINE OFF;
Insert into SIGDOLAGI.MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,PHONE,ADDR1,ADDR2,ZIPCODE,MAILING,SMS,GRADE,REGIDATE) values ('foo@gmail.com','1234','foo','i am foo!','01012345678','경기도 하남시 위례동','포례샤인','1234','f','f','Normal',to_date('23/12/07','RR/MM/DD'));
Insert into SIGDOLAGI.MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,PHONE,ADDR1,ADDR2,ZIPCODE,MAILING,SMS,GRADE,REGIDATE) values ('bar@gmail.com','1234','bar','i am bar!','01012345678','서울 송파구 위례동','로제비앙','1234','f','f','Normal',to_date('23/12/07','RR/MM/DD'));
Insert into SIGDOLAGI.MEMBER (EMAIL,PASSWORD,NAME,NICKNAME,PHONE,ADDR1,ADDR2,ZIPCODE,MAILING,SMS,GRADE,REGIDATE) values ('baz@gmail.com','1234','bar','i am bar!','01012345678','서울 송파구 위례동','로제비앙','1234','f','f','Normal',to_date('23/12/07','RR/MM/DD'));
REM INSERTING into SIGDOLAGI.MYPAGE
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.NOTICEBOARD
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.PHOTOBOARD
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.PLACE
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.PLANNER
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.PRODUCT
SET DEFINE OFF;
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (1,'mealkit','바삭한 코코넛 쉬림프(1~2인)',7900,1000,'thumb1','detail','쿠커','img1_1','img1_2','img1_3','img1_4','img1_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (2,'mealkit','얼큰 왕만두전골(2인)',16900,1000,'thumb2','detail','쿠커','img2_1','img2_2','img2_3','img2_4','img2_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (3,'mealkit','서울식 소불고기',59900,0,'thumb4','detail','노랑식품','img3_1','img3_2','img3_3','img3_4','img3_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (4,'mealkit','명란솥밥(2인)',15900,0,'thumb3','detail','노랑식품','img4_1','img4_2','img4_3','img4_4','img4_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (5,'mealkit','야채 호떡볼(2인)',9900,0,'thumb5','detail','노랑식품','img5_1','img5_2','img5_3','img5_4','img5_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (6,'mealkit','씨앗 호떡볼(2인)',9900,0,'thumb6','detail','노랑식품','img6_1','img6_2','img6_3','img6_4','img6_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (7,'mealkit','제주 한라봉 크림새우(1~2인)',13900,0,'thumb7','detail','수라상','img7_1','img7_2','img7_3','img7_4','img7_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (8,'mealkit','얼큰 만두전골(2인)',13900,0,'thumb8','detail','수라상','img8_1','img8_2','img8_3','img8_4','img8_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (9,'mealkit','만두전골(2인)',16900,7000,'thumb9','detail','수라상','img9_1','img9_2','img9_3','img9_4','img9_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (10,'mealkit','산삼배양근 버섯전골(2인)',21900,8000,'thumb10','detail','수라상','img10_1','img10_2','img10_3','img10_4','img10_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (11,'mealkit','까치복 지리탕(2인)',21900,0,'thumb11','detail','쿠커','img11_1','img11_2','img11_3','img11_4','img11_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (12,'mealkit','기름떡볶이(1~2인)',5900,0,'thumb12','detail','쿠커','img12_1','img12_2','img12_3','img12_4','img12_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (13,'mealkit','토마호크 스테이크(2인)',69900,10000,'thumb13','detail','노랑식품','img13_1','img13_2','img13_3','img13_4','img13_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (14,'mealkit','감자 고슴도치',10900,0,'thumb14','detail','노랑식품','img14_1','img14_2','img14_3','img14_4','img14_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (15,'mealkit','미니 피자',15900,0,'thumb15','detail','노랑식품','img15_1','img15_2','img15_3','img15_4','img15_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (16,'mealkit','깐풍치킨(2인)',12900,5000,'thumb16','detail','노랑식품','img16_1','img16_2','img16_3','img16_4','img16_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (17,'mealkit','고매치킨(2인)',12900,5000,'thumb17','detail','수라상','img17_1','img17_2','img17_3','img17_4','img17_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (18,'mealkit','시원한 동태탕(2인)',14900,1000,'thumb19','detail','수라상','img18_1','img18_2','img18_3','img18_4','img18_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (19,'mealkit','얼큰한 꽂게탕(2인)',14900,0,'thumb20','detail','수라상','img19_1','img19_2','img19_3','img19_4','img19_5');
Insert into SIGDOLAGI.PRODUCT (PROD_IDX,CATEGORY,PROD_NAME,PROD_PRICE,PROD_SALE,PROD_THUMBNAIL,PROD_DETAIL,SELLER,IMG1,IMG2,IMG3,IMG4,IMG5) values (20,'mealkit','칼칼한 대구탕(2인)',16900,9000,'thumb20','detail','수라상','img20_1','img20_2','img20_3','img20_4','img20_5');
REM INSERTING into SIGDOLAGI.PRODUCTREPLY
SET DEFINE OFF;
REM INSERTING into SIGDOLAGI.PRODUCT_QNA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008429
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008429" ON "SIGDOLAGI"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008435
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008435" ON "SIGDOLAGI"."PRODUCT" ("PROD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008444
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008444" ON "SIGDOLAGI"."FREEBOARD" ("FREEBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008450" ON "SIGDOLAGI"."PHOTOBOARD" ("PHOTOBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008452
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008452" ON "SIGDOLAGI"."PLANNER" ("PLANNER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008460
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008460" ON "SIGDOLAGI"."CART" ("CART_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008482
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008482" ON "SIGDOLAGI"."PRODUCT_QNA" ("QNA_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008492
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008492" ON "SIGDOLAGI"."NOTICEBOARD" ("NOTICEBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008496
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008496" ON "SIGDOLAGI"."INQUIRYBOARD" ("INQUIRYBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008504
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008504" ON "SIGDOLAGI"."MARKETORDER" ("ORDER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008510
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008510" ON "SIGDOLAGI"."PRODUCTREPLY" ("REPLY_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008460
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008460" ON "SIGDOLAGI"."CART" ("CART_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008444
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008444" ON "SIGDOLAGI"."FREEBOARD" ("FREEBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008496
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008496" ON "SIGDOLAGI"."INQUIRYBOARD" ("INQUIRYBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008504
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008504" ON "SIGDOLAGI"."MARKETORDER" ("ORDER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008429
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008429" ON "SIGDOLAGI"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008492
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008492" ON "SIGDOLAGI"."NOTICEBOARD" ("NOTICEBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008450" ON "SIGDOLAGI"."PHOTOBOARD" ("PHOTOBOARD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008452
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008452" ON "SIGDOLAGI"."PLANNER" ("PLANNER_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008435
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008435" ON "SIGDOLAGI"."PRODUCT" ("PROD_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008510
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008510" ON "SIGDOLAGI"."PRODUCTREPLY" ("REPLY_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008482
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGDOLAGI"."SYS_C008482" ON "SIGDOLAGI"."PRODUCT_QNA" ("QNA_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."CART" ADD PRIMARY KEY ("CART_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."FAVORITE" MODIFY ("TNAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."FAVORITE" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREEBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."FREEBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."FREEBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."FREEBOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."FREEBOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."FREEBOARD" ADD PRIMARY KEY ("FREEBOARD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INQUIRYBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."INQUIRYBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."INQUIRYBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."INQUIRYBOARD" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."INQUIRYBOARD" ADD PRIMARY KEY ("INQUIRYBOARD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARKETORDER
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("ADDR2" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("PAYMENT_METHOD" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("PAYMENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" ADD PRIMARY KEY ("ORDER_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" MODIFY ("ZIPCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("ADDR2" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("MAILING" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("SMS" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."MEMBER" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGDOLAGI"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICEBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."NOTICEBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."NOTICEBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."NOTICEBOARD" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."NOTICEBOARD" ADD PRIMARY KEY ("NOTICEBOARD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHOTOBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" ADD PRIMARY KEY ("PHOTOBOARD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACE
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PLACE" MODIFY ("LOT_ADDR" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLACE" MODIFY ("ROAD_ADDR" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLACE" MODIFY ("PLACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLACE" MODIFY ("X_POINT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLACE" MODIFY ("Y_POINT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANNER
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PLANNER" ADD PRIMARY KEY ("PLANNER_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGDOLAGI"."PLANNER" MODIFY ("CATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLANNER" MODIFY ("PLAN_START" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLANNER" MODIFY ("PLAN_END" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLANNER" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PLANNER" MODIFY ("NICKNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("PROD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("PROD_THUMBNAIL" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("PROD_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT" ADD PRIMARY KEY ("PROD_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGDOLAGI"."PRODUCT" MODIFY ("SELLER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTREPLY
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" ADD PRIMARY KEY ("REPLY_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_QNA
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" MODIFY ("SECRET" NOT NULL ENABLE);
  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" ADD PRIMARY KEY ("QNA_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."CART" ADD FOREIGN KEY ("PROD_IDX")
	  REFERENCES "SIGDOLAGI"."PRODUCT" ("PROD_IDX") ENABLE;
  ALTER TABLE "SIGDOLAGI"."CART" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."FAVORITE" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FREEBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."FREEBOARD" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INQUIRYBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."INQUIRYBOARD" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARKETORDER
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."MARKETORDER" ADD FOREIGN KEY ("CART_IDX")
	  REFERENCES "SIGDOLAGI"."CART" ("CART_IDX") ENABLE;
  ALTER TABLE "SIGDOLAGI"."MARKETORDER" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MYPAGE
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."MYPAGE" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTOBOARD
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PHOTOBOARD" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACE
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PLACE" ADD FOREIGN KEY ("PLANNER_IDX")
	  REFERENCES "SIGDOLAGI"."PLANNER" ("PLANNER_IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANNER
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PLANNER" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTREPLY
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" ADD FOREIGN KEY ("PROD_IDX")
	  REFERENCES "SIGDOLAGI"."PRODUCT" ("PROD_IDX") ENABLE;
  ALTER TABLE "SIGDOLAGI"."PRODUCTREPLY" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_QNA
--------------------------------------------------------

  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" ADD FOREIGN KEY ("PROD_IDX")
	  REFERENCES "SIGDOLAGI"."PRODUCT" ("PROD_IDX") ENABLE;
  ALTER TABLE "SIGDOLAGI"."PRODUCT_QNA" ADD FOREIGN KEY ("EMAIL")
	  REFERENCES "SIGDOLAGI"."MEMBER" ("EMAIL") ENABLE;
